### ISSUE TITLE
Buna benzer bir şey yapmaya çalışıyorum. Eğer mümkünse yardım edebilir misiniz ? 

### ISSUE THREAD

**Issue by waspnesser** [WarF0rPeace/DiscordAccountCreator#1]
Issue bölümünün böyle yardım istemek için uygun olmadığını biliyorum ama size ulaşabileceğim  bir yer göremedim. Açıklayayım. Sizin kodunuza benzer bir şeyi bende dlive için yapmaya çalışıyorum, ama benim ki aynı zamanda izleyici sayısını arttırmaya da odaklı. Webdriver'lar ile yaptım fakat verimli değiller. Requests modülü ile yapmaya karar verdim  ama ben bu requests modülünde biraz yeniyim. Ağ trafiğini analiz ettim, fingerprint diye bir header var. Bu header birden bire ortaya çıkıyor(Benim gözlemlediğimce). Ve buna benzer birkaç tane daha var. Nasıl yapacağımı, bu fingerprinti nasıl elde edeceğimi bilemedim. İnternette araştırdım ama bir şey bulamadım. Geçen hafta pes etmiştim. Bir iki gün önce sizin repo'nuzu gördüm. Baktığımda aynı benim yapmaya çalıştığım gibi discord'da yapıyordunuz ve kodunuzda siz fingerprinti elde edebiliyordunuz. Size sormak istediğim bu fingerprint nasıl elde edilir, neyin nesidir ?.  Ve diğer anlamadığım şey ise kodunuzda elde ettiğiniz x-super-prop nedir ? Benim dlive için benzer bir şey bulmam gerekiyor mu ? Eğer yardım edebilirseniz çok makbule geçer. Eğer edemezseniz de yine de teşekkürler.

**Comment by WarF0rPeace** [comment]
discord üzerinden iletişime geçebilir misin? WarForPeace#8440

wasp ***@***.***>, 29 Mar 2021 Pzt, 18:20 tarihinde şunu
yazdı:
